### ISSUE TITLE
DNS hosts not working for Transparent proxy?

### ISSUE THREAD

**Issue by rny** [kuoruan/luci-app-v2ray#7]
Transparent proxy - Enabled
Transparent proxy - UDP traffic
 
DNS  section:

```
Hosts: abcdetest.com|52.206.55.67
```

test in LAN client

```
abcdetest.com’s server IP address could not be found.
```

**Comment by kuoruan** [comment]
The iptables rule only redirect all UDP traffic on port 53 to the proxy.

I'm not sure how the V2Ray DNS works https://www.v2ray.com/en/configuration/protocols/dns.html

**Comment by kuoruan** [comment]
Follow this guide:
1. Add a outbound: alias dns_out, protocol dns, tag dns_out
2. Enable internal DNS
3. Add a routing rule, alias redirect_dns_query, port 53, network udp, outbound tag dns_out

Enable them all, and try again.

**Comment by ttimasdf** [comment]
FYI: UDP traffic forwarding is **NOT** enabled by default inside the `transparent_proxy` inbound config. After following @kuoruan 's guide, it's also necessary to tick the box below. (I found it after go through the codes...)

Add some hints/tutorial for this issue is recommended. 😄 

![image](https://user-images.githubusercontent.com/2762704/60933342-6911b980-a2f4-11e9-80a4-d064d746fe47.png)

**Comment by ttimasdf** [comment]
After enabling UDP forwarding, v2ray failed to resolve upstream vmess proxy hostname because port 53 is forwarded to v2ray and finally become an infinite loop....

Recommanded settings:
1. enable DNS forwarding only, add at least one non-standard port DNS server in v2ray dns config (e.g. 208.67.220.220:5353)
2. OR hard-code proxy IP in outbound config
3. OR enable china routes (`direct_cn_ip` in route configs) and make proxy domain resolved by chinese dns (`114_dns_1` in dns configs)

**Comment by kuoruan** [comment]
Reopen this, since there are some problem with transparent proxy DNS udp traffic to non China IPs.

**Comment by ttimasdf** [comment]
Add a tutorial/wiki page/better default setting is sufficient, IMHO. It's more of v2ray's internal complexity.

> enable DNS forwarding only, add at least one non-standard port DNS server in v2ray dns config (e.g. 208.67.220.220:5353)

Enable DNS forwarding by default in `config inbound 'transparent_proxy'` and add OpenDNS 208.67.220.220:5353 replacing `config dns_server 'cf_dns_1'` could be an **out-of-the-box** clean DNS solution for everyone.

https://github.com/kuoruan/luci-app-v2ray/blob/3c717b4ab2ee23fe22f5d781bce6bd9ece0a3a89/root/etc/config/v2ray#L22-L25

**Comment by kuoruan** [comment]
On my device, transparent proxy DNS query to proxy server will get an empty response back, don't know why.

**Comment by kuoruan** [comment]
Seems fixed in new version, closing this.
