### ISSUE TITLE
Can't get v2ray version

### ISSUE THREAD

**Issue by Limezy** [kuoruan/luci-app-v2ray#89]
Hi, after trying installation of v2ray-core and luci-app-v2ray, I get an error that prevents me to use v2ray on my OpenWRT. The error appears on the field where I'm supposed to give the v2ray file link, and says "Can't get v2ray version".

Please note that because of available space on my router, I had to install the v2ray-core on the RAM. Because of that, the v2ray file is here :
/tmp/run/rpcd/uci-834726428b291fe84b0cc10e83021124/v2ray
I did symlink that location to /usr/bin, but it didn't solve the issue.

From your manual I understand that instead of installing v2ray-core, I could "only" download the v2ray file from the official release, but I don't know which one to download ?

Thanks

**Comment by kuoruan** [comment]
1. Try 
```
/tmp/run/rpcd/uci-834726428b291fe84b0cc10e83021124/v2ray --version
```
see if the bin file runs well.

2. Change the bin file path in LuCi from ```/usr/bin/v2ray``` to ```/tmp/run/rpcd/uci-834726428b291fe84b0cc10e83021124/v2ray```.

3. Need your arch info:
```
opkg print-architecture
```

**Comment by tpaullee** [comment]
The label led me to specify the directory of the v2ray first time around. I ran into similar complaint with my specification /usr/bin/v2ray directory.  See attached png file.When I use /usr/bin/v2ray/v2ray for the exact v2ray binary file, the error disappeared and the version showed up.
I have a newifi3 D2 router from Taobao a few weeks back. I have not been successful in getting it to work.  One of the reason is that I am not inside of the gfw now and it is hard to tell how much progress I make. The outbound specification is completely wacky (see the second png file) even though I have a good /root/config.json file that I tried on my Linux client.  Any suggestion/insight will be very welcome.
My luci-app-v2ray version is fast out-of-date with recent releases, and I need to re-base my pkg soon to try again.
 

    On Tuesday, January 7, 2020, 08:46:45 AM PST, Limezy <notifications@github.com> wrote:  
 
 
Hi, after trying installation of v2ray-core and luci-app-v2ray, I get an error that prevents me to use v2ray on my OpenWRT. The error appears on the field where I'm supposed to give the v2ray file link, and says "Can't get v2ray version".

Please note that because of available space on my router, I had to install the v2ray-core on the RAM. Because of that, the v2ray file is here :
/tmp/run/rpcd/uci-834726428b291fe84b0cc10e83021124/v2ray
I did symlink that location to /usr/bin, but it didn't solve the issue.

From your manual I understand that instead of installing v2ray-core, I could "only" download the v2ray file from the official release, but I don't know which one to download ?

Thanks

**Comment by Limezy** [comment]
@kuoruan many thanks for your fast reply. I'll try all your proposals tonight when I come back home
@tpaullee we can't see your PNGs

**Comment by tpaullee** [comment]
I checked my "Sent" folder.  It is there... Hmmm confused.Try again in this email...  May be there is something I don't know about with these github emails.
 

    On Tuesday, January 7, 2020, 08:01:19 PM PST, Limezy <notifications@github.com> wrote:  
 
 
@kuoruan many thanks for your fast reply. I'll try all your proposals tonight when I come back home
@tpaullee we can't see your PNGs

**Comment by StoneMoe** [comment]
Ran out of memory can also led to "Can't get v2ray version" problem because of `v2ray -version` will failed to launch.

**Comment by Limezy** [comment]
@StoneMoe I guess you are right, this may be the problem I have.
I'm planning to buy a good router. If it works I'll close this thread

**Comment by Jehoshwa** [comment]
When install V2Ray-core-mini <=4.42.x, everything is ok

root@Openwrt:~# /usr/bin/v2ray --version
V2Ray 4.41.1 (OpenWrt) R1 (go1.16.7 linux/arm)
A unified platform for anti-censorship.

But when install V2Ray-core-mini >= 4.43.x

root@Openwrt:~# /usr/bin/v2ray --version
Error relocating /usr/bin/v2ray: __nanosleep_time64: symbol not found

I've tried several times in my router with 512MB RAM and no other apps installed.
